### ISSUE TITLE
Feature request preview_image in Backend Preview

### ISSUE THREAD

**Issue by ses2013** [Hauer-Heinrich/hh_video_extender#1]
Hi there,
thx for the extender. Is there a way to show the preview_image in the Backend Preview ? I can't resolve the Relations to it properly.
Thanks for any hint.
Stefan

**Comment by Teisi** [comment]
How did you change the preview in the backend (hook or mod. or ...)?
From your own custom content element or from an existing one, for example textmedia?

**Comment by ses2013** [comment]
Hi, it is actually a hook of the textmedia in the bootstrap_package.
Its tricky because of the relation of a relation, right?

**Comment by ses2013** [comment]
And rendert in Fluid …

**Comment by Teisi** [comment]
did you do this like: https://blog.teamgeist-medien.de/2016/04/backendvorschau-fuer-eigene-inhaltselemente-mit-flexform.html

then i will check this...

**Comment by ses2013** [comment]
Yes kind of …

**Comment by Teisi** [comment]
in the linked method (hook) you can add something like:
```
$fluidTmpl->assign('row', $row);

$fileRepository = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Resource\FileRepository::class);
$assets = $fileRepository->findByRelation('tt_content', 'assets', $row['uid']);
foreach ($assets as $key => $value) {
        $assets['prevImage'] = $fileRepository->findByRelation('sys_file_reference', 'preview_image', $value->getUid());
}
DebuggerUtility::var_dump($assets);
```

**Comment by ses2013** [comment]
OK suuper: I get the path to the file now. 
How would I make a Thumbnail out of it either in den Hook or in Fluid ?
Thx this should be the last step …

**Comment by Teisi** [comment]
i would make this in fluid <f:image or <f:media ...

**Comment by ses2013** [comment]
Not perfect but works. As there can be only 1 preview_image.
<img alt="Video Thumb" src="/fileadmin/{Thumb.prevImage.0.originalFile.identifier}" width="128" height="c128" />
Thanks for your help.

**Comment by Teisi** [comment]
you can have more than one preview image if you like - you have to overwrite the TCA definition (Configuration/TCA/Overrides/.... in your own extension / theme.
And you should still adapt / optimize the above-mentioned code. For example with an "IF" if ever a preview picture exists - and the preview picture also assign to the correct "main" picture/video.
