### ISSUE TITLE
Can't update extension to 1.6 because of wrong version tag 1.51?

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_video_extender#10]
Hi,

I wanted to update the extension to v1.6 (from 1.51) via composer but this didn't work.
"Nothing to Install" was the answer.

```
$ ddev composer update hauerheinrich/hh-video-extender
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Setting up TYPO3 environment and extensions.
```

I guess that happend because version 1.51 is higher than version 1.6 and so composer thinks that I already have the newest version? I think the correct version would have been version 1.5.1 or newer versions have to continue with version 1.52, ...

Another question I have: Will TYPO3 10.4 LTS be supported?

**Comment by Teisi** [comment]
Should be fixed already

**Comment by mbrodala** [comment]
As mentioned in the TYPO3 Slack: 1.6 should have been 1.60 (or 2.0) instead. (1.6 < 1.51 < 1.60)
