### ISSUE TITLE
Dependency problem with TYPO3 10

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [Hauer-Heinrich/hh_video_extender#14]
Hi,

just stumbled over a dependency problem with hh-video-extender, where I cannot update because there is no ^10.4.99 of TYPO3:

- hauerheinrich/hh-video-extender 0.1.62 requires typo3/cms-core ^9.5.0 || ^10.4.99 -> found typo3/cms-core[v9.5.0, ..., v9.5.24] but it conflicts with your root composer.json require (^10.4).

So

•	typo3/cms-core: ^9.5.0 || ^10.4.99
•	typo3/cms-fluid: ^9.5.0 || ^10.4.99
•	typo3/cms-fluid-styled-content: ^9.5.0 || ^10.4.99
•	typo3/cms-frontend: ^9.5.0 || ^10.4.99

should be

•	typo3/cms-core: ^9.5.0 || ^10.4.0
•	typo3/cms-fluid: ^9.5.0 || ^10.4.0
•	typo3/cms-fluid-styled-content: ^9.5.0 || ^10.4.0
•	typo3/cms-frontend: ^9.5.0 || ^10.4.0

I guess.

Greetings

**Comment by Teisi** [comment]
should be fixed with version 0.1.63

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Yes, thanks!
