### ISSUE TITLE
Several errors regarding FileReference class extended

### ISSUE THREAD

**Issue by instruccionesaldorso** [Hauer-Heinrich/hh_video_extender#2]
This line:
https://github.com/Hauer-Heinrich/hh_video_extender/blob/master/ext_localconf.php#L23
has no effect, as there is no TYPO3\\CMS\\Core\\FileReference class, but a class TYPO3\\CMS\\Core\\Resource\\FileReference

The class Classes/Resource/FileReference.php is wrong as well. Line https://github.com/Hauer-Heinrich/hh_video_extender/blob/master/Classes/Resource/FileReference.php#L11 should extend \TYPO3\CMS\Core\Resource\FileReference and not TYPO3\CMS\Core\FileReference (note that backslash that it should be at the beginning).
Besides that, the class contains an unknown method $this->initStorageObjects() over line https://github.com/Hauer-Heinrich/hh_video_extender/blob/master/Classes/Resource/FileReference.php#L28

**Comment by Teisi** [comment]
You're right, but this code is not needed at all (for current version).
The code section has been deleted.

**Comment by Teisi** [comment]
Thanks for your feedback :)
