### ISSUE TITLE
[Question] TYPO3 11 support

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_video_extender#22]
Are there plans to support TYPO3 11.5 as well?

**Comment by Teisi** [comment]
yes, and we work on PHP8 support.

**Comment by the-andyman** [comment]
Is there an approximate time window when a new version for TYPO3 11 could be released?

**Comment by Teisi** [comment]
so actually the current version already works with TYPO3 11 and PHP 8, or do you have any problems / errors?
