### ISSUE TITLE
[Error] Undefined array key "hh_video_extender"

### ISSUE THREAD

**Issue by bh-teufels** [Hauer-Heinrich/hh_video_extender#38]
**Describe the bug**
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "hh_video_extender" in /app/vendor/hauerheinrich/hh-video-extender/ext_localconf.php line 8

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "hh_video_extender" in /app/vendor/hauerheinrich/hh-video-extender/Configuration/TCA/Overrides/sys_template.php line 8
```

**Environment:**
 - TYPO3 12.4.1 
 - PHP 8.2
 - hh_video_extender 0.2.0

**Additional context**
Problem with PHP 8.2

**Fix**
change 
`if ($GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extensionKey]['config']['typoScript'] === '0') {`
in ext_localconf.php line 8 and sys_template.php line 8 to
`if (isset($GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extensionKey]) && $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extensionKey]['config']['typoScript'] === '0') {`

**Comment by Teisi** [comment]
Thank you!
Should be fixed with version 0.2.1 :)
