### ISSUE TITLE
preview image for html5 video is not shown in frontend

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_video_extender#7]
Hi,

I wanted to include some videos and I added a `preview_image` for each video. The `poster` attribute with the image is not rendered, it's missing.

Can someone confirm this issue?

I use TYPO3 9.5.13 and the latest version of the hh_video_extender.

**Comment by Teisi** [comment]
poster-attribute image is only outputted if preload is set to "none" - so you can now set "plugin.tx_hhvideoextender.settings.showAllwaysPreviewImageAsImage = 1" (or constants-editor) to have allways a preview image as an additional img-tag.
So you can do what you want with it (with css and or js) :)

@medarob please try the new version 1.6 did this work for you?

**Comment by medarob** [comment]
I will test the new version. Thank you.

Additionally, there also seems to be a problem in Chrome with the poster-attribute. You have to set preload to "metadata" or "none" to make it work: https://support.google.com/chrome/thread/15245443?hl=en
`auto` (which is now the default value in the extension) does not work in Chrome.

In Firefox all options seems to work, even if `metadata` seems to be the default option.
`The default value is different for each browser. The spec advises it to be set to metadata.`

Can you change the default value to `metadata` because this seems to work in most browsers. Otherwise the user has to change the settings everytime from `auto` to `metadata` to make it work in Chrome.

**Comment by Teisi** [comment]
You should be able to configure the default value by yourself if you need this:
https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/UserTsconfig/TcaDefaults.html :) 

or with TCEMAIN like:
TCEMAIN.table.sys_file_reference.preload = 2 // or something like that...
-------
currently not tested...
